import json
import os

# Path to the feedback log generated by the AI Reasoning service
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_PATH = os.path.join(BASE_DIR, "../ai_reasoning/feedback_log.json")

def retrieve_lessons():
    if not os.path.exists(LOG_PATH):
        return "No past lessons found."
    
    lessons = []
    try:
        with open(LOG_PATH, "r") as f:
            for line in f:
                data = json.loads(line)
                if data.get("decision") == "accepted":
                    lessons.append(f"- Accepted decision: {data.get('comments')}")
    except Exception:
        pass
    
    if not lessons:
        return "No relevant lessons found."
    
    # Return the most recent 5 lessons
    return "\n".join(lessons[-5:])